"""Write pipeline/bone_maps/divider_to_vt2_warrior.json from the Divider's own skeleton (183 joints, mostly unnamed).

    python pipeline/bone_maps/make_divider_to_warrior.py extracted/ds2/divider

The Divider is four creatures held together: its arms are the hand-creatures' tails (handLeft_tail07 at the
shoulder ... tail01 at the hand, then the creature's body m_spine1-3 and fingers), and its hands, feet and head
hang off the root, not off the torso. So the map re-parents each creature onto the torso, then swings the whole
arm about the shoulder towards the Chaos Warrior's hand (keeping the Divider's long reach). Everything else is
assigned by creature prefix, or by the nearest named ancestor for the unnamed joints (spikes, tentacles, flap).
"""
import json, os, re, sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import ds2_geo  # noqa: E402

src = sys.argv[1]
rcb = ds2_geo.load_stream_rcb(src)
skel = next(s for s in rcb["skeletons"] if s["name"] == "divider_main")
geos = {k: g for k, g in ds2_geo.load_stream_geos(src).items() if len(g["bones"]) == len(skel["parents"])}
hashes = {b["rcb_index"]: b["hash"] for g in geos.values() for b in g["bones"]}
known = [l.strip() for l in open(os.path.join(os.path.dirname(__file__), "..", "ds2_bone_names.txt"), encoding="utf-8")
         if l.strip() and not l.startswith("#")]
table = {ds2_geo.name_hash(w): w for w in known}
names = [table.get(hashes.get(i), f"bone_{i:02d}") for i in range(len(skel["parents"]))]
parent = {names[i]: (names[p] if p >= 0 else None) for i, p in enumerate(skel["parents"])}

SIDE = {"Left": "left", "Right": "right"}
FIXED = {
    "m_root": "j_hips", "torso_m_spine1": "j_hips", "torso_m_spine2": "j_spine1", "torso_m_spine3": "j_spine1",
    "torso_m_neck": "j_neck",
    "torso_l_clav": "j_leftshoulder", "torso_l_shoulder": "j_leftarm",
    "torso_r_clav": "j_rightshoulder", "torso_r_shoulder": "j_rightarm",
    "torso_l_hip": "j_leftupleg", "torso_l_knee": "j_leftleg", "torso_l_ankle": "j_leftfoot",
    "torso_r_hip": "j_rightupleg", "torso_r_knee": "j_rightleg", "torso_r_ankle": "j_rightfoot",
}


def weights(n):
    if n in FIXED:
        return FIXED[n]
    m = re.match(r"hand(Left|Right)_(.*)", n)
    if m:
        side, part = SIDE[m.group(1)], m.group(2)
        t = re.match(r"tail0?(\d+)", part)
        if t:  # the arm: tail07 at the shoulder ... tail01 at the hand
            return f"j_{side}arm" if int(t.group(1)) >= 5 else f"j_{side}forearm"
        return f"j_{side}hand"
    m = re.match(r"foot(Left|Right)_", n)
    if m:
        return f"j_{SIDE[m.group(1)]}foot"
    if n.startswith("head_"):
        return "j_head"
    p = parent[n]  # unnamed: shoulder spikes, spine tentacles and flap, toes, face
    while p is not None and p.startswith("bone_"):
        p = parent[p]
    if p in ("torso_l_shoulder", "torso_l_clav"):
        return "j_leftshoulder"
    if p in ("torso_r_shoulder", "torso_r_clav"):
        return "j_rightshoulder"
    if p == "torso_m_spine3":
        return "j_spine1"
    return weights(p) if p else "j_hips"


bones = {n: {"weights": weights(n)} for n in names}
# put the separate creatures onto the torso before fitting
for side, s in (("Left", "l"), ("Right", "r")):
    bones[f"hand{side}_m_spine1"]["parent"] = f"torso_{s}_shoulder"
    bones[f"foot{side}_m_spine1"]["parent"] = f"torso_{s}_ankle"
bones["head_m_body"]["parent"] = "torso_m_neck"
# shoulder spikes stay on the clavicle, so they don't swing down with the arm
for n in names:
    if n.startswith("bone_") and parent[n] in ("torso_l_shoulder", "torso_r_shoulder"):
        bones[n]["parent"] = parent[parent[n]]
# fit: hips onto the warrior's hips; legs aimed (the two are the same height); arms swung about the shoulder
bones["torso_m_spine1"].update(head="j_hips")
for s, side in (("l", "left"), ("r", "right")):
    bones[f"torso_{s}_hip"].update(head=f"j_{side}upleg", aim=f"j_{side}leg", tail_to=f"torso_{s}_knee")
    bones[f"torso_{s}_knee"].update(head=f"j_{side}leg", aim=f"j_{side}foot", tail_to=f"torso_{s}_ankle")
    hand = "Left" if s == "l" else "Right"
    bones[f"torso_{s}_shoulder"].update(head=f"j_{side}arm", aim=f"j_{side}hand", tail_to=f"hand{hand}_m_spine1",
                                        rigid=True)

base = json.load(open(os.path.join(os.path.dirname(__file__), "slasher_to_vt2_human.json"), encoding="utf-8"))
out = {"about": "How rig_onto_host.py fits the Dead Space 2 Divider (skeleton divider_main) onto the Chaos Warrior. "
                "Generated by make_divider_to_warrior.py; edit that script, not this file.",
       "fields": base["fields"], "rotate_z_degrees": 180, "bones": bones}
path = os.path.join(os.path.dirname(__file__), "divider_to_vt2_warrior.json")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(json.dumps(out, indent=1) + "\n")
counts = {}
for b in bones.values():
    counts[b["weights"]] = counts.get(b["weights"], 0) + 1
print(f"wrote {path}: {len(bones)} rows; joints used: {dict(sorted(counts.items()))}")
