"""Generate the mod's data files from the sheets. Each sheet row becomes one Lua table entry.

Run from the repo root:  python tools/generate.py           (refuses while any cell is unfilled or reference broken)
                         python tools/generate.py --draft   (generates anyway; rows without bones stay inactive)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from preflight import ROOT, load, preflight, read_bones  # noqa: E402

MOD = os.path.join(ROOT, "mod", "dsv2")
SCRIPTS = os.path.join(MOD, "scripts", "mods", "dsv2")
HEADER = "-- GENERATED by tools/generate.py from sheets/*.json. Edit the sheets, not this file.\n"


def lua(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, list):
        return "{ " + ", ".join(lua(v) for v in value) + " }"
    raise TypeError(value)


def bones_for(row):
    path = os.path.join(ROOT, row["bones_file"])
    return read_bones(path) if os.path.isfile(path) else []


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def generate(draft):
    skins, props, settings = load("enemy_skins"), load("props"), load("settings")
    players, weapons = load("player_skins"), load("weapon_skins")

    out = [HEADER, "local SKINS = { breeds = {}, templates = {}, careers = {}, weapons = {} }\n"]
    for row in skins["rows"]:
        links = [[bone, bone] for bone in bones_for(row)]
        out.append(
            f"-- {row['id']}: {row['source_model']} on {row['breed']} ({row['why']}; jank {row['jank']})\n"
            f"SKINS.breeds.{row['breed']} = {{\n"
            f"\tid = {lua(row['id'])},\n\tskin_unit = {lua(row['skin_unit'])},\n\tscale = {lua(row['scale'])},\n"
            f"\thide_inventory = {lua(row['hide_inventory'])},\n\tsetting = {lua(row['setting'])},\n"
            f"\tlinks = {{ {', '.join(lua(l) for l in links)} }},\n}}\n")
    for row in props["rows"]:
        out.append(
            f"-- {row['id']}: {row['source_model']} replaces {row['host_unit']}\n"
            f"SKINS.templates.{row['unit_template']} = {{\n"
            f"\tid = {lua(row['id'])},\n\tskin_unit = {lua(row['skin_unit'])},\n\tscale = {lua(row['scale'])},\n"
            f"\thide_inventory = false,\n\tsetting = {lua(row['setting'])},\n"
            f"\tlinks = {{ {', '.join(lua(l) for l in row['link_nodes'])} }},\n}}\n")
    for row in players["rows"]:  # SKINS.careers.<career>.<first_person|third_person>
        links = [[bone, bone] for bone in bones_for(row)]
        out.append(
            f"-- {row['id']}: {row['source_model']} on {row['career']} ({row['view']})\n"
            f"SKINS.careers.{row['career']} = SKINS.careers.{row['career']} or {{}}\n"
            f"SKINS.careers.{row['career']}.{row['view']} = {{\n"
            f"\tid = {lua(row['id'])},\n\tskin_unit = {lua(row['skin_unit'])},\n\tscale = {lua(row['scale'])},\n"
            f"\thide_inventory = false,\n\tsetting = {lua(row['setting'])},\n"
            f"\tlinks = {{ {', '.join(lua(l) for l in links)} }},\n}}\n")
    for row in weapons["rows"]:  # SKINS.weapons.<AttachmentNodeLinking key>.<first_person|third_person>
        out.append(
            f"-- {row['id']}: {row['source_model']} replaces {row['node_linking']} ({row['view']})\n"
            f"SKINS.weapons.{row['node_linking']} = SKINS.weapons.{row['node_linking']} or {{}}\n"
            f"SKINS.weapons.{row['node_linking']}.{row['view']} = {{\n"
            f"\tid = {lua(row['id'])},\n\tskin_unit = {lua(row['skin_unit'])},\n\tscale = {lua(row['scale'])},\n"
            f"\thide_inventory = false,\n\tsetting = {lua(row['setting'])},\n"
            f"\tlinks = {{ {', '.join(lua(l) for l in row['link_nodes'])} }},\n}}\n")
    out.append("\nreturn SKINS\n")
    write(os.path.join(SCRIPTS, "dsv2_skins.lua"), "".join(out))

    widgets = "".join(
        f"\t\t\t{{ setting_id = {lua(r['id'])}, type = {lua(r['type'])}, default_value = {lua(r['default'])} }},\n"
        for r in settings["rows"])
    write(os.path.join(SCRIPTS, "dsv2_data.lua"), HEADER +
          'local mod = get_mod("dsv2")\n\nreturn {\n'
          '\tname = "Necromorph Tide",\n'
          '\tdescription = mod:localize("mod_description"),\n'
          '\tis_togglable = true,\n'
          '\toptions = {\n\t\twidgets = {\n' + widgets + '\t\t},\n\t},\n}\n')

    loc = ['\tmod_description = {\n\t\ten = "Dead Space 2 Necromorphs replace Vermintide 2 enemies. Private build.",\n\t},\n']
    for r in settings["rows"]:
        loc.append(f"\t{r['id']} = {{\n\t\ten = {lua(r['title'])},\n\t}},\n")
        loc.append(f"\t{r['id']}_description = {{\n\t\ten = {lua(r['tooltip'])},\n\t}},\n")
    write(os.path.join(SCRIPTS, "dsv2_localization.lua"), HEADER + "return {\n" + "".join(loc) + "}\n")

    # Only units that exist in the SDK project can go in the package, or the build fails.
    rows = skins["rows"] + props["rows"] + players["rows"] + weapons["rows"]
    # Variant rows (shield, commander) share their base row's skin unit; list each unit once.
    units = list(dict.fromkeys(r["skin_unit"] for r in rows if r["rigged"] is True))
    unit_block = "".join(f'\t"{u}"\n' for u in units)
    write(os.path.join(MOD, "resource_packages", "dsv2", "dsv2.package"), (
        "lua = [\n\t\"scripts/mods/dsv2/*\"\n]\n" + (f"\nunit = [\n{unit_block}]\n" if units else "")))
    print(f"generated {len(skins['rows'])} enemy skins, {len(props['rows'])} props, {len(players['rows'])} player skins, {len(weapons['rows'])} weapon skins, "
          f"{len(settings['rows'])} settings; {len(units)} units in the package")


def main():
    draft = "--draft" in sys.argv
    unfilled, unverified, broken = preflight()
    # Unverified status columns (rigged / tested_in_game) are checked after building, so they don't block it.
    if broken or (unfilled and not draft):
        print("Preflight is not clean; run tools/preflight.py. Use --draft to generate anyway.")
        return 1
    generate(draft)
    return 0


if __name__ == "__main__":
    sys.exit(main())
