-- GENERATED by tools/generate.py from sheets/*.json. Edit the sheets, not this file.
local SKINS = { breeds = {}, templates = {} }
-- slasher_fanatic: slasher on chaos_fanatic (basic melee horde, human skeleton; jank low)
SKINS.breeds.chaos_fanatic = {
	id = "slasher_fanatic",
	skin_unit = "units/dsv2/slasher_fanatic/slasher_fanatic",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- slasher_marauder: slasher on chaos_marauder (basic melee horde, human skeleton; jank low)
SKINS.breeds.chaos_marauder = {
	id = "slasher_marauder",
	skin_unit = "units/dsv2/slasher_marauder/slasher_marauder",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- slasher_gor: slasher on beastmen_gor (Beastmen horde melee; jank medium)
SKINS.breeds.beastmen_gor = {
	id = "slasher_gor",
	skin_unit = "units/dsv2/slasher_gor/slasher_gor",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_beastmen",
	links = {  },
}
-- pack_slave: pack on skaven_slave (small, fast, swarming, weak; jank medium)
SKINS.breeds.skaven_slave = {
	id = "pack_slave",
	skin_unit = "units/dsv2/pack_slave/pack_slave",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- pack_ungor: pack on beastmen_ungor (small scrawny swarm, better size match; jank medium)
SKINS.breeds.beastmen_ungor = {
	id = "pack_ungor",
	skin_unit = "units/dsv2/pack_ungor/pack_ungor",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_beastmen",
	links = {  },
}
-- twitcher_monk: twitcher on skaven_plague_monk (frenzied fast flurries; jank medium)
SKINS.breeds.skaven_plague_monk = {
	id = "twitcher_monk",
	skin_unit = "units/dsv2/twitcher_monk/twitcher_monk",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- enhanced_stormvermin: enhanced_slasher on skaven_storm_vermin (armoured tougher grunt; jank medium)
SKINS.breeds.skaven_storm_vermin = {
	id = "enhanced_stormvermin",
	skin_unit = "units/dsv2/enhanced_stormvermin/enhanced_stormvermin",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- enhanced_raider: enhanced_slasher on chaos_raider (armoured tougher grunt; jank low)
SKINS.breeds.chaos_raider = {
	id = "enhanced_raider",
	skin_unit = "units/dsv2/enhanced_raider/enhanced_raider",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- leaper_runner: leaper on skaven_gutter_runner (lunges and pins; jank medium)
SKINS.breeds.skaven_gutter_runner = {
	id = "leaper_runner",
	skin_unit = "units/dsv2/leaper_runner/leaper_runner",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- stalker_bestigor: stalker on beastmen_bestigor (charges and knocks down; jank low)
SKINS.breeds.beastmen_bestigor = {
	id = "stalker_bestigor",
	skin_unit = "units/dsv2/stalker_bestigor/stalker_bestigor",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_beastmen",
	links = {  },
}
-- exploder_globadier: exploder on skaven_poison_wind_globadier (runs at you and blows up near death; jank high)
SKINS.breeds.skaven_poison_wind_globadier = {
	id = "exploder_globadier",
	skin_unit = "units/dsv2/exploder_globadier/exploder_globadier",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- puker_warpfire: puker on skaven_warpfire_thrower (close-range cone of spew; jank high)
SKINS.breeds.skaven_warpfire_thrower = {
	id = "puker_warpfire",
	skin_unit = "units/dsv2/puker_warpfire/puker_warpfire",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- lurker_ratling: lurker on skaven_ratling_gunner (hangs back and sprays; jank high)
SKINS.breeds.skaven_ratling_gunner = {
	id = "lurker_ratling",
	skin_unit = "units/dsv2/lurker_ratling/lurker_ratling",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- spitter_archer: spitter on beastmen_ungor_archer (ranged attacker hanging back; jank medium)
SKINS.breeds.beastmen_ungor_archer = {
	id = "spitter_archer",
	skin_unit = "units/dsv2/spitter_archer/spitter_archer",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_beastmen",
	links = {  },
}
-- infector_leech: infector on chaos_corruptor_sorcerer (creepy caster that grabs you; jank medium)
SKINS.breeds.chaos_corruptor_sorcerer = {
	id = "infector_leech",
	skin_unit = "units/dsv2/infector_leech/infector_leech",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- brute_minotaur: brute on beastmen_minotaur (huge charging bull; jank medium)
SKINS.breeds.beastmen_minotaur = {
	id = "brute_minotaur",
	skin_unit = "units/dsv2/brute_minotaur/brute_minotaur",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_beastmen",
	links = {  },
}
-- brute_ogre: brute on skaven_rat_ogre (huge charging bruiser (Brute variant); jank medium)
SKINS.breeds.skaven_rat_ogre = {
	id = "brute_ogre",
	skin_unit = "units/dsv2/brute_ogre/brute_ogre",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_skaven",
	links = {  },
}
-- tripod_spawn: tripod on chaos_spawn (tentacle grab that pulls you in; jank medium)
SKINS.breeds.chaos_spawn = {
	id = "tripod_spawn",
	skin_unit = "units/dsv2/tripod_spawn/tripod_spawn",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- ubermorph_troll: ubermorph on chaos_troll (regenerates, won't stay down; jank high)
SKINS.breeds.chaos_troll = {
	id = "ubermorph_troll",
	skin_unit = "units/dsv2/ubermorph_troll/ubermorph_troll",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- divider_warrior: divider on chaos_warrior (tall armoured, hard to drop; jank medium)
SKINS.breeds.chaos_warrior = {
	id = "divider_warrior",
	skin_unit = "units/dsv2/divider_warrior/divider_warrior",
	scale = 1.0,
	hide_inventory = true,
	setting = "faction_chaos",
	links = {  },
}
-- marker_banner: marker_shard replaces units/weapons/enemy/wpn_bm_standard_01/wpn_bm_standard_01_placed
SKINS.templates.standard_unit = {
	id = "marker_banner",
	skin_unit = "units/dsv2/marker_banner/marker_banner",
	scale = 1.0,
	hide_inventory = false,
	setting = "marker_banner",
	links = { { 0, 0 } },
}

return SKINS
