-- GENERATED by tools/generate.py from sheets/*.json. Edit the sheets, not this file.
return {
	mod_description = {
		en = "Dead Space 2 Necromorphs replace Vermintide 2 enemies. Private build.",
	},
	faction_chaos = {
		en = "Chaos become Necromorphs",
	},
	faction_chaos_description = {
		en = "Slashers, Enhanced Slashers, Infector, Tripod, Ubermorph, Divider. Applies to enemies that spawn after you change it.",
	},
	faction_skaven = {
		en = "Skaven become Necromorphs",
	},
	faction_skaven_description = {
		en = "The Pack, Twitchers, Leapers, Exploders, Pukers, Lurkers, Brute variant. Applies to enemies that spawn after you change it.",
	},
	faction_beastmen = {
		en = "Beastmen become Necromorphs",
	},
	faction_beastmen_description = {
		en = "Slashers, the Pack, Stalkers, Spitters, Brute. Applies to enemies that spawn after you change it.",
	},
	marker_banner = {
		en = "Marker banners",
	},
	marker_banner_description = {
		en = "Beastmen war banners become Marker shards. Applies to enemies that spawn after you change it.",
	},
}
