-- GENERATED by tools/generate.py from sheets/*.json. Edit the sheets, not this file.
local mod = get_mod("dsv2")

return {
	name = "Necromorph Tide",
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{ setting_id = "faction_chaos", type = "checkbox", default_value = true },
			{ setting_id = "faction_skaven", type = "checkbox", default_value = true },
			{ setting_id = "faction_beastmen", type = "checkbox", default_value = true },
			{ setting_id = "marker_banner", type = "checkbox", default_value = true },
		},
	},
}
